### PR TITLE
Allow multiple after and before injections per definition

### PR DESCRIPTION
**Pull request by sergiou87**

### CODE REVIEW

**Comment by alexgarbarev** [comment]
Thanks for contribution. What the reason of that changes? Why don't you use sequence of `injectMethod` calls instead?
When I thought about multiple before and after injection, I decided that any order can be done via `injectMethod` apporach.

**Comment by jasperblues** [comment]
@ sergiou87 Any issues with Aleksey's suggestion? Does it work for you?

**Comment by sergiou87** [comment]
Sorry @alexgarbarev I totally missed that comment! :confounded: You're totally right, I guess my contribution is completely useless, sorry! :sweat_smile:

**Comment by jasperblues** [comment]
@sergiou87 No problem! Thanks so much for using Typhoon. We look forward to another contribution in future :) :+1:

**Comment by jasperblues** [comment]
Just noticed: 

```objc
NSMutableSet *_injectedMethods;
```

This does not imply any order. Rather than allow multiple before/after we should let method injections occur in order, as @alexgarbarev suggested. 

I thought this was already implemented, but its not.

**Comment by alexgarbarev** [comment]
Ah.. Right. I thought it was ```NSMutableOrderedSet ```. Will fix that soon

**Comment by alexgarbarev** [comment]
@jasperblues fixed

**Comment by jasperblues** [comment]
@alexgarbarev  great!

**Pull request closed without merging**
