### PR TITLE
Fix slow [factory registerDefinition:] method.

### PR DESCRIPTION
**Pull request by warnyul**
I described my solution here: #325

### CODE REVIEW

**Comment by jasperblues** [comment]
Thanks @warnyul !! Great work

**Comment by psekara** [comment]
It now crashes on iOS7 due to usage of NSString containsString: method

[https://github.com/appsquickly/Typhoon/blame/master/Source/Utils/TyphoonIntrospectionUtils.m#L151]

**Comment by warnyul** [comment]
I'm sorry I did not notice. I fixed it and created a new pull request.

**Comment by alexgarbarev** [comment]
@warnyul 
> // Little bit faster than protocol_isEqual method.
Where is proof about that? As I understand, protocol_isEqual is just pointer comparation instead of string full text search.. isn't true?

**Comment by alexgarbarev** [comment]
@warnyul 

```objc
+ (NSSet *)propertiesForClass:(Class)clazz upToParentClass:(Class)parent
{
    NSString *key = NSStringFromClass(clazz);

    if (propertiesCache == nil) {
        propertiesCache = [NSMutableDictionary dictionary];
    }
    else {
        if ([[propertiesCache allKeys] containsObject:key]) {
            return [propertiesCache objectForKey:key];
        }
    }
```
Is cache really needed there? As I understand, objective-c runtime does caching automatically when you introspect same class few times (then this cache release automatically by system).

Another problem here is same cache for different input arguments, because cache key isn't related on `parent` argument. 

For example this equation always true in current code.

```objc
[TyphoonIntrospectionUtils propertiesForClass:[Assembly class] upToParentClass:[AssemblyParent class]] 
==
[TyphoonIntrospectionUtils propertiesForClass:[Assembly class] upToParentClass:[NSObject class]]
```

**Comment by alexgarbarev** [comment]
@warnyul 

```objc
- (void)_loadOnlyOne:(TyphoonDefinition *)definition
{
    [self preparePostProcessors];
    [_definitionPostProcessors enumerateObjectsUsingBlock:^(id<TyphoonDefinitionPostProcessor> postProcessor, NSUInteger idx, BOOL *stop) {
        [postProcessor postProcessDefinition:definition withFactory:self];
    }];
    [self newOrScopeCachedInstanceForDefinition:definition args:nil];
}
```

Calling line below is incorrect here. Because if definition scope is not singleton, this will produce new instance of definition when it's unexpectable. 
```objc
[self newOrScopeCachedInstanceForDefinition:definition args:nil];
```

I faced with that bug in my current project. Prototype-scoped definition was created twice for one injection, but it was designed to be created once (network call at init time).

**Pull request merged**
