### PR TITLE
Storyboard definitions

### PR DESCRIPTION
**Pull request by etolstoy**
This pull request fixes Issue #404 and introduces new family of factory methods for `TyphoonDefinition`:

``` objc
+ (id)withStoryboardName:(NSString *)storyboardName storyboardId:(NSString *)storyboardId;
+ (id)withStoryboardName:(NSString *)storyboardName storyboardId:(NSString *)storyboardId configuration:(TyphoonDefinitionBlock)injections;
+ (id)withStoryboard:(id)storyboard storyboardId:(NSString *)storyboardId;
+ (id)withStoryboard:(id)storyboard storyboardId:(NSString *)storyboardId configuration:(TyphoonDefinitionBlock)injections;
```

Under the hood they use `TyphoonFactoryDefinition` to create a `UIViewController` using a `- instantiateViewControllerWithIdentifier:` method, with a `UIStoryboard` posing as a controllers factory.

Besides it, I changed the way Singleton scopes are applied to ViewController's. Currently, if there is a retained singleton instance in one of the component pools, it will be returned from the `UIStoryboard` instead of a new instance.

Unfortunately, these changes **can break backwards compatibility**, because it changes the way how singleton ViewControllers are handled. Do you have any ideas how to deal with it?

### CODE REVIEW

**Comment by igrekde** [comment]
@alexgarbarev Nice idea about caching UIStoryboards, it's definitely much more efficient. And what exactly do you mean under `Another problem is when user creates TyphoonStoryboard outside, and expect TyphoonStoryboard for given identifier.`? 

What are your thoughts about backwards compatibility in this case?

**Comment by alexgarbarev** [comment]
I reviewed the code, looks really cool! :+1:

> Another problem is when user creates TyphoonStoryboard outside, and expect TyphoonStoryboard for given identifier.

My thoughts was:
1) User created some storyboard with name, for example `Settings.storyboard`. And then he keep in mind "this storyboard would be attached to my settings typhoon assembly", so he creates `TyphoonStoryboard` instance with assembly manually.
2) He uses own `TyphoonStoryboard` instance in his code
3) He wrote definition inside his "settings" assembly, which refers to "Settings" storyboard
4) Right now, Typhoon will create UIStoryboard with same name "Settings" and all created viewController s wouldn't be injected

**Comment by alexgarbarev** [comment]
> Unfortunately, these changes can break backwards compatibility, because it changes the way how singleton ViewControllers are handled. Do you have any ideas how to deal with it?

> What are your thoughts about backwards compatibility in this case?

What problems can happens here?
I see only next problem: 
1) User has definition for some `UIViewController` and this definition has LazySingletone scope 
2) User has ViewController of that kind in his storyboard.
He expect new ViewController creation by storyboard, but getting same every time. 

What is correct behavior here?

**Comment by igrekde** [comment]
@alexgarbarev Thanks for reviewing! 🙂

> 4) Right now, Typhoon will create UIStoryboard with same name "Settings" and all created viewController s wouldn't be injected.

`TyphoonStoryboardResolver` always swizzles `UIStoryboards` with appropriate `TyphoonStoryboard` instances, so in the method:
```objc
+ (id)withStoryboardName:(NSString *)storyboardName storyboardId:(NSString *)storyboardId configuration:(TyphoonDefinitionBlock)injections
{
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:storyboardName
                                                         bundle:[NSBundle mainBundle]];
    return [self withStoryboard:storyboard storyboardId:storyboardId configuration:injections];
}
```
...the `TyphoonStoryboard` is created, activated with `factoryForResolvingUI`. So, basically, it will provide the same behaviour as `TyphoonStoryboard`, created manually.

By the way, I don't see any use cases, when the user may benefit from using `TyphoonStoryboard` directly. Right now it's just an implementation detail.

> I see only next problem: 
> 1) User has definition for some UIViewController and this definition has LazySingletone scope 
> 2) User has ViewController of that kind in his storyboard.
> He expect new ViewController creation by storyboard, but getting same every time.
> What is correct behavior here?

The correct behaviour, as it seems to me, is the one we've just implemented - if you have a `Singleton` definition for a certain `UIViewController`, then it's pretty logical to get the same instance every time you instantiate it from storyboard.

The problem is, that a lot of apps already use the current implementation, just as you've described, and may broke eventually. The most dangerous part is that they won't get any crashes - it's rather tricky to notice, that you are working with the same instance every time.

**Comment by alexgarbarev** [comment]
Regarding backwards compatibility,  
We can look for cached instances, made by our Storyboard Definitions only _(speaking of that, I think better to have separate class for TyphoonStoryboardDefinition, inherited from TyphoonFactoryDefinition, instead of just TyphoonFactoryDefinition - in that case we can find Storyboard definitions at anytime by enumeration)._ Can by implemented by checking `TyphoonDefinition` kind, before returning from `definitionForInstance:typhoonKey:` method

But.. I think API would be not great then.. Ideally Storyboard should be apart from regular TyphoonDefinitions and works with TyphoonStoryboardDefinitions only, but this affects current apps heavily..

**Comment by alexgarbarev** [comment]
> ...the TyphoonStoryboard is created, activated with factoryForResolvingUI. So, basically, it will provide the same behaviour as TyphoonStoryboard, created manually.

True, but only if that storyboard name specified in the plist (i.e. returned by `collectStoryboardsFromBundle` method)

>The correct behaviour, as it seems to me, is the one we've just implemented - if you have a Singleton definition for a certain UIViewController, then it's pretty logical to get the same instance every time you instantiate it from storyboard.
The problem is, that a lot of apps already use the current implementation, just as you've described, and may broke eventually. The most dangerous part is that they won't get any crashes - it's rather tricky to notice, that you are working with the same instance every time.

I think we should force users to use new definitions for that cases. Maybe we can crash app (using NSAssert which crashes only on debug build, or checking for DEBUG macro), when we see old-style UIViewController definition usage in TyphoonStoryboard

**Comment by igrekde** [comment]
Maybe it's better to delay merging this feature into master, unless we decide to release a new major version of Typhoon (with a couple of other breaking changes).

A separate definition may help - it doesn't influence the public API, just implementation details. It also ensures, that only appropriate definitions will be used when working with storyboards.

> True, but only if that storyboard name specified in the plist (i.e. returned by collectStoryboardsFromBundle method)

This method returns the names of all storyboards found in the main bundle of the application, instead ones listed under `TyphoonCleanStoryboards` in the `Info.plist`. Here we use the concept of black-listing instead of white-listing, so that users can adopt this feature easier.

**Comment by alexgarbarev** [comment]
> Nice idea about caching UIStoryboards, it's definitely much more efficient
I think we need some registry of all storyboards we are currently using. I think we can do that in the `storyboardWithName:bundle:` swizzled method. Just register weak reference somewhere and use that inside storyboard factory. 

Speaking of TyphoonFactoryDefinition + Storyboard, I imagine custom factory instance which returns `UIViewController` by `storyboardName`, `viewControllerIdentifier` as input

**Comment by alexgarbarev** [comment]
> This method returns the names of all storyboards found in the main bundle of the application, instead ones listed under TyphoonCleanStoryboards in the Info.plist. Here we use the concept of black-listing instead of white-listing, so that users can adopt this feature easier.

Ah, make sense. I forgot about that :-)

Yeah. Delayed release can help here, because we have a choice: "bad, but backward compatible"  vs "good and breaking"

**Comment by alexgarbarev** [comment]
Ok, I did some code review yesterday, I have some notes, see below:

**1. EXC_BAD_ACCESS crash**

The reason of that crash because `TyphoonStoryboardDefinition` has `initializer`property (it's default is `init` method) - Typhoon automatically adds `init` initializer to all definitions without that. The solution is to override `initializer` property getter and return `nil` in all cases for that kind of definition.

If you want more details about exact problem, look at `@implementation TyphoonComponentFactory (InstanceBuilder)` file, following method:

```objc
- (id)initializeInstanceWithDefinition:(TyphoonDefinition *)definition args:(TyphoonRuntimeArguments *)args
{
    __block id instance = [definition targetForInitializerWithFactory:self args:args];
    if (definition.initializer && instance) {
        BOOL isClass = IsClass(instance);

        TyphoonInjectionContext *context = [[TyphoonInjectionContext alloc] initWithFactory:self args:args
            raiseExceptionIfCircular:YES];
        context.classUnderConstruction = isClass ? (Class)instance : [instance class];

        [definition.initializer createInvocationWithContext:context completion:^(NSInvocation *invocation) {
            if (isClass && ![definition.initializer isClassMethodOnClass:context.classUnderConstruction]) {
                instance = [invocation typhoon_resultOfInvokingOnAllocationForClass:context.classUnderConstruction];
            } else {
                instance = [invocation typhoon_resultOfInvokingOnInstance:instance];
            }
        }];

    }
    return instance;
}
```

You can see here, that if `initializer` is not `nil`, it creates invocation for that method and calls on instance. Result of that invocation overrides `instance` variable value.

What does it mean for us? Well, let's review retain count rules first.

 > **Retain count rules**
In the retain count objective-c model, some methods increase internal retain counter, such methods as `retain`, `new`, `copy`, `alloc` etc, makes you responsible to release object. You can also mark your custom method to follow that rule via `NS_RETURNS_RETAINED` attribute macro. With ARC environment that means that ARC will decrease retainCount (via `release`) on returned instance. Basically, if you do 
```
id instance = [[Object alloc] init];
```
your instance retainCount will be 1. `alloc] init]` gives you 1, then storing into `instance` var gives you one more, so `retainCount` should be 2, but ARC will balance that calling `release` because method is `alloc`

So, we got our instance passed though `init` method initializer and returned by `typhoon_resultOfInvokingOnInstance:` method. Default `init` method returns self itself, so doesn't affect to retainCount, but `typhoon_resultOfInvokingOnInstance` method marked as `NS_RETURNS_RETAINED` and ARC will call extra `release` here. We can see that instance was extra released without reason.. oops!

The only solution is:
we should return `nil` in `initializer` getter for `TyphoonStoryboardDefinition`

_other review points follow in next few hours/days_

**Comment by alexgarbarev** [comment]
** 2. stroryboardId **

What do you think about storyboardId parameter name? I was confused seeing `storyboardName` and `storyboardId` at same place. `StoryboardId` was confused as storyboard's id, instead of viewController's id inside storyboard.
What do you think? Maybe we can rename that into something like `viewControllerId` or anything better?

** 3. TyphoonViewControllerFactory lifecycle **

I'm not sure (and it's minor thing), but maybe we can avoid frequent object creation by using singleton pattern for `TyphoonViewControllerFactory`. (since `factory` can be easily moved to factory method parameter)
What is your thoughts here?

** 4.  StoryboardId and StoryboardName parameters nil checks **

Right now app will crash with hard-understanble NSDictionaries crashes, when StoryboardName is nil. Also that happens only while ViewController instantiation - I think better to catch these user errors faster. Let's throw human-understanble exceptions here.

** 4 (enhancement) use TyphoonAbstractInjection instead of NSString for storyboardId and storyboardName**

Let's use TyphoonAbstractInjection approach instead of NSString. That makes these params more powerful: they could be runtime arguments, string can be evaluated from another definition etc.. (see kinds of typhoon injections)

** 5. Avoid viewController prototype instantiation if viewController for Id already cached **

If viewController is cached inside singletons pool, we can avoid prototype creation then. Now I see problems:
* User's code for viewController's alloc/init and dealloc will be fired extra time, each time when viewController appears. <-- Can confuse, and lead problems in case of bad users code
* ViewController loading supposed to be expensive operation - we can improve performance here.

** 6. Fire warnings when `withClass:configuration` used with Storyboard **

We can check for class here, and promote user to use our new TyphoonStoryboardDefinitions as more preferred way (because uses storyboards pool). What do you think? I know this can mess our codebase, but maybe it's good for user?

** 7. Make Storyboards pool store weak reference **

I believe that can be too surprised for user: he can face with memory problem because Typhoon stores all his storyboards forever. Lets use weak reference as more transparent way - only user cached one if it's stored by user. We can use `TyphoonWeakComponentsPool` implementation for that

**Comment by etolstoy** [comment]
@alexgarbarev I've finally found some time to finish this feature! 🎉 Once again, thanks for the wonderful review. I've fixed all of the aforementioned issues.

I'll give it a test in my current project - and if everything is fine, I think we can merge it :)

**Comment by vasilenkoigor** [comment]
@alexgarbarev @etolstoy I'm reviewed PR in test project. Works fine 👍

**Comment by etolstoy** [comment]
Thanks, @vasilenkoigor! I think, we can merge this feature then. @alexgarbarev, what do you think?

**Pull request merged**
