### PR TITLE
TyphoonNibLoader (analog of TyphoonStoryboard for nib)

### PR DESCRIPTION
**Pull request by dani-gavrilov**
`TyphoonNibLoader` is an analog of `TyphoonStoryboard`, but for nibs, and has the same interface.

Initialize: 

```
+ (TyphoonNibLoader *)nibLoaderWithBundle:(NSBundle *)bundleOrNil;
+ (TyphoonNibLoader *)nibLoaderWithFactory:(id<TyphoonComponentFactory>)factory bundle:(NSBundle *)bundleOrNil;
```

Use:

```
- (__kindof UIViewController *)instantiateViewControllerWithIdentifier:(NSString *)nibName;
```

You can use this the same way as TyphoonStoryboard:

```
// LaunchModuleAssembly

- (CustomModuleFactory *)factoryCustomModule {
    return [TyphoonDefinition withClass:[CustomModuleFactory class]
                          configuration:^(TyphoonDefinition *definition) {
                              [definition useInitializer:@selector(initWithNibLoader:andNibName:)
                                              parameters:^(TyphoonMethod *initializer) {
                                                  [initializer injectParameterWith:[self nibLoaderLaunchModule]];
                                                  [initializer injectParameterWith:@"CustomModuleViewController"];
                                              }];
                          }];
}

- (id)nibLoaderLaunchModule {
    return [TyphoonDefinition withClass:[TyphoonNibLoader class]
                          configuration:^(TyphoonDefinition *definition) {
                              [definition useInitializer:@selector(nibLoaderWithFactory:bundle:)
                                              parameters:^(TyphoonMethod *initializer) {
                                                  [initializer injectParameterWith:self];
                                                  [initializer injectParameterWith:nil];
                                              }];
                          }];
}

// CustomModuleFactory

- (UIViewController *)destinationViewController {
    UIViewController *destinationViewController = [self.nibLoader instantiateViewControllerWithIdentifier:self.nibName];
    return destinationViewController;
}
```

Also next categories:

```
UIViewController (TyphoonStoryboardIntegration)
UIView (TyphoonDefinitionKey)
```

and inject properties logic and methods are moved from `TyphoonStoryboard.m` to a new class `TyphoonViewControllerInjector` which is used now in `TyphoonStoryboard` and `TyphoonNibLoader`.

You can use `TyphoonViewControllerInjector` this way:

```
- (void)injectPropertiesForViewController:(UIViewController *)viewController withFactory:(id<TyphoonComponentFactory>)factory;
```

### CODE REVIEW

**Comment by jasperblues** [comment]
Great work @dani-gavrilov !! Can we have an integration test showing this working pls? Any unit tests you feel appropriate would also be appreciated.

**Comment by dani-gavrilov** [comment]
@jasperblues sure! I'll do this as soon as possible.

**Comment by dani-gavrilov** [comment]
I'm finished with tests. Could you please take a look?

**Comment by alexgarbarev** [comment]
Hey @dani-gavrilov, it's finally merged (together with another PR) but not in master yet.
I preparing typhoon v4 release (core was rewritten to avoid lots of swizzling and boost startup performance). If you still using Typhoon, please check on your project using:
```
pod 'Typhoon', :git => 'https://github.com/appsquickly/Typhoon.git', :tag => 'v4'
```
And confirm NibLoader and other features works as expected

**Comment by dani-gavrilov** [comment]
Hey @alexgarbarev 
All works as expected. Thanks.

**Pull request merged**
