### PR TITLE
Another iOS-specific TyphoonClassFromString performance optimization

### PR DESCRIPTION
**Pull request by skeeet**
Second part of #432

### CODE REVIEW

**Comment by skeeet** [comment]
@jasperblues not much to do there regarding formatting though. Reasonable refactor would be split move implementation to another function, and have two different implementations depending on platform.
Something like this:
```
#if TARGET_OS_IOS
Class TyphoonClassFromFrameworkString(NSString *className) {
...iOS specific code here...
}
#else
Class TyphoonClassFromFrameworkString(NSString *className) {
...OSX specific code here...
}
#elif
```

Just didn't wanted to introduce more functions and mess with internal api.
Any suggestions?

**Comment by jasperblues** [comment]
@skeeet Your suggestion sounds good.

**Comment by skeeet** [comment]
Well, looks a little better now

**Comment by jasperblues** [comment]
Thanks so much @skeeet :beers: . . . really appreciate your work.

**Pull request merged**
