### PR TITLE
Added tvOS support

### PR DESCRIPTION
**Pull request by belkevich**
Hello,

I've added tvOS support. Please, merge it and push to cocoapods

P.S. Let me know if there any problems, I'll fix it

### CODE REVIEW

**Comment by jasperblues** [comment]
Thanks @belkevich !! I'm pushing a new micro version to CocoaPods for you.

**Comment by jasperblues** [comment]
@belkevich Oops, there appears to be a problem with the release I just pushed. If you're using TyphoonConfig, things might not work as expected. Fix coming ASAP.

**Comment by Air7Y** [comment]
Hi, @jasperblues  are you sure that you push podSpec to cocoapods? Because when i "pod search Typhoon" it gives me version 3.4.5 and the fix for TVos is in 3.4.7.

**Comment by jasperblues** [comment]
Yes, because we pushed 3.4.6 first and that caused things to break :P 

how about pod install/update - work for you?

**Comment by Air7Y** [comment]
thanx @jasperblues , it was issue with my cocoapods 1.0.0, install & update was not helping, resolve it with:
1. sudo rm -fr ~/.cocoapods/repos/master
2. pod setup

Now im testing (3.4.7) version in TVOS environment and it seams to be working good !

**Comment by jasperblues** [comment]
👍 great :)

**Pull request merged**
